# Setup
title:          "Gradem Blog"
description:    "Official blog for Gradem."
url:            "https://blog.gradem.io"
future:         true
permalink:      pretty

# Pagination
paginate:       5

# Sass converter configuration
sass:
  style:        compressed

# Local Server
host:           localhost # same as default value '127.0.0.1' but reads better

# Links
main:           "http://gradem.io/auth/register"
expo:           "https://expo.getbootstrap.com"
themes:         "https://themes.getbootstrap.com"

# Social
authors:        "Robert Lee"
author:
  twitter:      "grademapp"

twitter:
  card:         "summary_large_image"
  username:     "getbootstrap"

logo:           "/assets/img/bootstrap-social.png"

# Output
defaults:
  - scope:
      path:     ""
    values:
      image:
        path:   "/assets/img/bootstrap-social.png" # default image
        width:  1200
        height: 630

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache
  - .netlify
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
